import React from 'react';
import { BarChart, Download, Filter } from 'lucide-react';

export function Reports() {
  const reports = [
    {
      id: 1,
      title: "Monthly Patient Statistics",
      department: "All Departments",
      generatedBy: "Dr. Sarah Wilson",
      date: "2025-04-01",
      type: "Statistical",
      status: "completed"
    },
    {
      id: 2,
      title: "Emergency Room Capacity Report",
      department: "Emergency",
      generatedBy: "Dr. Michael Brown",
      date: "2025-04-01",
      type: "Operational",
      status: "pending"
    },
    // Add more reports as needed
  ];

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
        <button className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
          <BarChart className="h-5 w-5" />
          Generate Report
        </button>
      </div>

      <div className="flex gap-4 mb-6">
        <button className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">
          <Filter className="h-5 w-5 text-gray-500" />
          Filter Reports
        </button>
      </div>

      <div className="grid gap-6 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
        {reports.map((report) => (
          <div key={report.id} className="bg-white rounded-xl shadow-sm p-6">
            <div className="flex justify-between items-start mb-4">
              <div>
                <h3 className="text-lg font-semibold text-gray-900">{report.title}</h3>
                <p className="text-sm text-gray-500">{report.department}</p>
              </div>
              <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                <Download className="h-5 w-5 text-gray-500" />
              </button>
            </div>
            
            <div className="space-y-3">
              <div>
                <p className="text-sm text-gray-500">Generated by</p>
                <p className="text-sm font-medium text-gray-900">{report.generatedBy}</p>
              </div>
              
              <div>
                <p className="text-sm text-gray-500">Date</p>
                <p className="text-sm font-medium text-gray-900">
                  {new Date(report.date).toLocaleDateString('en-US', {
                    year: 'numeric',
                    month: 'long',
                    day: 'numeric'
                  })}
                </p>
              </div>

              <div className="flex justify-between items-center pt-4 border-t">
                <span className="text-sm font-medium text-gray-500">{report.type}</span>
                <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium capitalize
                  ${report.status === 'completed' ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'}`}>
                  {report.status}
                </span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}